### PR TITLE
Initialize js

### PR DESCRIPTION
**Pull request by KeithBillings**
new file!

### CODE REVIEW

**Review by MarkKelly00 — COMMENTED** [review]
nice JS

**Review by MarkKelly00 — COMMENTED** [review]
NICE JS!!

**Review by BrianSoldani — COMMENTED** [review]
Looks great

**Review by BrianSoldani — APPROVED** [review]
now approved

**Review by MarkKelly00 — APPROVED** [review]
NICE JS!!!!

**Pull request merged**
